- name: copy rpm for logstash
  copy:
    src: files/logstash-7.3.0.rpm
    dest: /tmp/logstash-7.3.0.rpm
  tags: init-logstash

- name: install logstash rpm
  yum:
    name: /tmp/logstash-7.3.0.rpm
    state: present
  tags: init-logstash

- name: copy logstash systemd config
  copy:
    src: templates/logstash.systemd.service
    dest: /etc/systemd/system/logstash.service
    mode: 0644
  tags: init-logstash

- name: install some plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-input-websocket

- name: make pipeline.d
  file:
    path: /etc/logstash/pipeline.d/
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: init-logstash

- name: init logstash config
  template:
    src: "{{ item.src }}"
    dest: "/etc/logstash/{{ item.destpath }}"
  tags: init-logstash
  loop:
    - { src: 'templates/jvm.options', destpath: 'jvm.options'}
    - { src: 'templates/logstash.yml', destpath: 'logstash.yml'}
    - { src: 'templates/pipelines.yml', destpath: 'pipelines.yml'}
  notify:
  - systemd start logstash

- name: sync pipelines.yml
  template:
    src: "{{ item.src }}"
    dest: "/etc/logstash/{{ item.destpath }}"
  tags: sync-logstash
  loop:
    - { src: 'templates/jvm.options', destpath: 'jvm.options'}
    - { src: 'templates/logstash.yml', destpath: 'logstash.yml'}
    - { src: 'templates/pipelines.yml', destpath: 'pipelines.yml'}

- name: sync pipelines config
  copy:
    src: "files/pipeline.d/{{ item }}"
    dest: "/etc/logstash/pipeline.d/{{ item }}"
  tags: sync-logstash
  loop:
    - bdg.conf
    - op.conf
    - project.conf
    - ai.conf
    - arch.conf
